### ISSUE TITLE
Crashes on screen change on android

### ISSUE THREAD

**Issue by T-Dynamos** [kivy-garden/frostedglass#5]
Hi @DexerBR 
Running it works fine on linux, but on andoird crashes.
Logs:
```
02-25 21:19:32.749  3928  3971 I python  :  Traceback (most recent call last):
02-25 21:19:32.750  3928  3971 I python  :    File "/home/tdynamos/SnowFlakes/.buildozer/android/app/main.py", line 212, in <module>
02-25 21:19:32.752  3928  3971 I python  :    File "/home/tdynamos/SnowFlakes/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/snowflakes/armeabi-v7a/kivy/app.py", line 956, in run
02-25 21:19:32.754  3928  3971 I python  :    File "/home/tdynamos/SnowFlakes/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/snowflakes/armeabi-v7a/kivy/base.py", line 574, in runTouchApp
02-25 21:19:32.756  3928  3971 I python  :    File "/home/tdynamos/SnowFlakes/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/snowflakes/armeabi-v7a/kivy/base.py", line 339, in mainloop
02-25 21:19:32.757  3928  3971 I python  :    File "/home/tdynamos/SnowFlakes/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/snowflakes/armeabi-v7a/kivy/base.py", line 379, in idle
02-25 21:19:32.759  3928  3971 I python  :    File "/home/tdynamos/SnowFlakes/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/snowflakes/armeabi-v7a/kivy/clock.py", line 733, in tick
02-25 21:19:32.763  3928  3971 I python  :    File "/home/tdynamos/SnowFlakes/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/snowflakes/armeabi-v7a/kivy/clock.py", line 776, in post_idle
02-25 21:19:32.768  3928  3971 I python  :    File "kivy/_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
02-25 21:19:32.770  3928  3971 I python  :    File "kivy/_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
02-25 21:19:32.772  3928  3971 I python  :    File "kivy/_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
02-25 21:19:32.773  3928  3971 I python  :    File "kivy/_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
02-25 21:19:32.776  3928  3971 I python  :    File "/home/tdynamos/SnowFlakes/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/snowflakes/armeabi-v7a/kivy_garden/frostedglass/__init__.py", line 413, in _update_glsl
02-25 21:19:32.777  3928  3971 I python  :    File "/home/tdynamos/SnowFlakes/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/snowflakes/armeabi-v7a/kivy_garden/frostedglass/__init__.py", line 682, in not_current_screen
02-25 21:19:32.778  3928  3971 I python  :  AttributeError: 'NoneType' object has no attribute 'current'
```
I am using frostedglass in 2nd screen.
One time screen change works, but on next change it crahses. 

Android : 11
Frostedglass branch : develop
Python : 3.9

Screenshots:
![image](https://user-images.githubusercontent.com/68729523/221367070-fb2f4387-7929-4523-b2c9-d19d6ed19ef4.png)

This is my second screen I can only switch it once. Switching next time it crashes
My second screen:
```python
MDScreen:
    name:"right"
    md_bg_color:app.theme_cls.opposite_bg_light
    Image:
        id:bg
        source:app.background_image
        keep_ratio:False
        allow_stretch:True
        anim_delay:0.05
    FrostedGlass:
        id:main
        background:bg
        blur_size:30
        noise_opacity:0
        luminosity:1
        saturation:1.2
        overlay_color:app.theme_cls.bg_light[:-1] + [0.1]
        outline_color:0,0,0,0
    MDBoxLayout:
        size_hint:0.9,0.06
        md_bg_color:1,1,1,0.3
        radius:[dp(15)] * 4
        pos_hint:{"center_x":0.5,"center_y":0.92}
        outline_color:app.theme_cls.bg_dark[:-1] + [0.6]     
        outline_width:dp(0.1)
        AnchorLayout:
            size_hint:0.15,1
            MDIconButton:
                icon:"magnify"
                theme_icon_color:"Custom"
                icon_color:1,1,1,1
                valgin:"center"
                icon_size:"20sp"
                ripple_scale:0
        AnchorLayout:
            size_hint:0.8,1
            TextInput:
                size_hint:1,0.8
                foreground_color:app.theme_cls.bg_light
                background_color:[0] * 4
                font_name:app.medium_font
                multiline:False
                hint_text:"Search in your apps"
                hint_text_color:1,1,1,0.4
                font_size:"15sp"
                cursor_color:app.theme_cls.bg_light
    MDBoxLayout:
        size_hint:None,None
        size:dp(150),dp(150)
        md_bg_color:1,1,1,0.3
        radius:[dp(20)] * 4
        pos_hint:{"center_x":0.26,"center_y":0.72}
    MDBoxLayout:
        size_hint:None,None
        size:dp(150),dp(150)
        md_bg_color:1,1,1,0.3
        radius:[dp(20)] * 4
        pos_hint:{"center_x":0.74,"center_y":0.72}
    CustomGrid:
        name:root.name
```

**Comment by DexerBR** [comment]
Hi @T-Dynamos!

Could you test the `develop` branch and see if the error still happens?

**Comment by T-Dynamos** [comment]
No its same:
```
02-26 19:59:37.056  7419  7561 I python  :  Traceback (most recent call last):
02-26 19:59:37.056  7419  7561 I python  :    File "/home/tdynamos/SnowFlakes/.buildozer/android/app/main.py", line 212, in <module>
02-26 19:59:37.093  7419  7561 I python  :    File "/home/tdynamos/SnowFlakes/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/snowflakes/armeabi-v7a/kivy/app.py", line 956, in run
02-26 19:59:37.095  7419  7561 I python  :    File "/home/tdynamos/SnowFlakes/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/snowflakes/armeabi-v7a/kivy/base.py", line 574, in runTouchApp
02-26 19:59:37.097  7419  7561 I python  :    File "/home/tdynamos/SnowFlakes/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/snowflakes/armeabi-v7a/kivy/base.py", line 339, in mainloop
02-26 19:59:37.099  7419  7561 I python  :    File "/home/tdynamos/SnowFlakes/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/snowflakes/armeabi-v7a/kivy/base.py", line 379, in idle
02-26 19:59:37.100  7419  7561 I python  :    File "/home/tdynamos/SnowFlakes/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/snowflakes/armeabi-v7a/kivy/clock.py", line 733, in tick
02-26 19:59:37.102  7419  7561 I python  :    File "/home/tdynamos/SnowFlakes/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/snowflakes/armeabi-v7a/kivy/clock.py", line 776, in post_idle
02-26 19:59:37.104  7419  7561 I python  :    File "kivy/_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
02-26 19:59:37.105  7419  7561 I python  :    File "kivy/_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
02-26 19:59:37.108  7419  7561 I python  :    File "kivy/_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
02-26 19:59:37.110  7419  7561 I python  :    File "kivy/_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
02-26 19:59:37.112  7419  7561 I python  :    File "/home/tdynamos/SnowFlakes/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/snowflakes/armeabi-v7a/kivy_garden/frostedglass/__init__.py", line 413, in _update_glsl
02-26 19:59:37.114  7419  7561 I python  :    File "/home/tdynamos/SnowFlakes/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/snowflakes/armeabi-v7a/kivy_garden/frostedglass/__init__.py", line 682, in not_current_screen
02-26 19:59:37.115  7419  7561 I python  :  AttributeError: 'NoneType' object has no attribute 'current'
```
Used url: https://github.com/kivy-garden/frostedglass/archive/refs/heads/develop.zip

Previously I used https://github.com/DexerBR/frostedglass/archive/refs/heads/develop.zip. I forgot to mention that I used fork from your account because it was not working when using this branch. (Got from the PR #4 which is now merged). 

I can also give apk for testing where to send?

**Comment by T-Dynamos** [comment]
Are you able to reproduce it? I am also calling update_effect() on screen change.

**Comment by DexerBR** [comment]
@T-Dynamos Could you test #6?

**Comment by T-Dynamos** [comment]
Removing update_effect() fixed the error btw. But I will also test this.

**Comment by DexerBR** [comment]
> Removing update_effect() fixed the error btw. But I will also test this.

The fix should work, even using `update_effect()`

**Comment by T-Dynamos** [comment]
Works!
